# Test goal: Newest ICC CPU-only build
# Test intents (should change rarely and conservatively):
#   OS: Ubuntu oldest supported
#   Compiler: ICC newest supported
#   FFT: MKL
#   GPU: no
#   Scope: configure, build, unit tests, regression tests
# Test implementation choices (free to change as needed):
#   OS: Ubuntu 18.04
#   Build type: Debug
#   Compiler: ICC 2021.1
#   MPI: thread_MPI
#   SIMD: AVX2_256
#   Parallelism nt/ntomp: 4/2

gromacs:icc-2021.1:configure:
  # Test SIMD: AVX2_256
  # Test FFT: MKL
  # Test scope: configure
  extends:
   - .gromacs:base:configure
   - .use-icc-oneapi:base
   - .rules:merge-and-post-merge-acceptance
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-18.04-gcc-7-oneapi-2021.1.1
  variables:
    CMAKE: /usr/local/cmake-3.17.2/bin/cmake
    COMPILER_MAJOR_VERSION: 2021

gromacs:icc-2021.1:build:
  extends:
    - .variables:default
    - .gromacs:base:build
    - .use-icc-oneapi:base
    - .rules:post-merge-acceptance
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-18.04-gcc-7-oneapi-2021.1.1
  variables:
    CMAKE: /usr/local/cmake-3.17.2/bin/cmake
  needs:
    - job: gromacs:icc-2021.1:configure

gromacs:icc-2021.1:test:
  extends:
    - .gromacs:base:test
    - .use-icc-oneapi:base
    - .rules:post-merge-acceptance
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-18.04-gcc-7-oneapi-2021.1.1
  variables:
    CMAKE: /usr/local/cmake-3.17.2/bin/cmake
  needs:
    - job: gromacs:icc-2021.1:build

gromacs:icc-2021.1:regressiontest:
  extends:
    - .gromacs:base:regressiontest
    - .use-icc-oneapi:base
    - .rules:post-merge-acceptance
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-18.04-gcc-7-oneapi-2021.1.1
  variables:
    CMAKE: /usr/local/cmake-3.17.2/bin/cmake
  needs:
    - job: gromacs:icc-2021.1:build
    - job: regressiontests:prepare

